### ISSUE TITLE
参考 jfinal Db + Record模式

### ISSUE THREAD

**Issue by cmdares** [chenrenfei/sagacity-sqltoy#10]
jfinal Db + Record 模式独步天下，如果针对大量数据表进行简单操作，弄出来一大堆bo vo service的确费时费力，没啥价值。数据结构增加字段后，还得一通更改代码。可否吸取一下这方面的优势，继续简化sql层之上的操作，提供更为便捷的使用方法。比如对于查询而言，以前使用spring jdbc template ，给sql 返回List(Map)其实也很香，简单的场景，后台代码量可以降解到只有三个文件，1个controller，1个后台访问类，1个XML（项目所有sql），最多加个拦截器。个人也向往极简程序，希望作者可以再进行优化。
感谢。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chenrenfei** [comment]
我们有一个sagacity-rainbow项目，里面是用xml配置模式组合多个操作的，但目前使用场景更多偏向查询，为其他系统提供查询服务。

我之前的想法是用sagacity-rainbow来完成所有服务，但想法和现实还是比较远的。
目前的主流还是springcloud或spring boot+dubbo 这种微服务模式，大家更加偏向于自己写service，然后组织逻辑。

另外sqltoy里面提供了第三方系统集成的策略：

# 请参见org.sagacity.sqltoy.SqlToyContext 

```java
public class SqlToyContext implements ApplicationContextAware {
	/**
	 * @todo 提供可以动态增加解析sql片段配置的接口,并返回具体id,用于第三方平台集成，如报表平台等
	 * @param sqlSegment
	 * @return
	 * @throws Exception
	 */
	public synchronized SqlToyConfig parseSqlSegment(Object sqlSegment) throws Exception {
		return scriptLoader.parseSqlSagment(sqlSegment);
	}

}
```
