### ISSUE TITLE
关于生成工具和 setid问题

### ISSUE THREAD

**Issue by sglmsn** [chenrenfei/sagacity-sqltoy#13]
版本:4.10.5
生成工具默认把bigint(20) 给了 Types.Integer, 使用的雪花算法自动设置,会出现转换错误.

然后就是 id 字段 的set方法不允许 public Long setId(Long id)这样的链式形式, 否则会提醒找不到setid 这个方法.

**Comment by chenrenfei** [comment]
1、检查ID在数据库中是否设置为主键了。
2、quickvo.xml 里面需要配置
```xml

<primary-key>
	<table name="SQLTOY_\w+|SYS_\w+" strategy="generator" generator="default" />
        <!-- 这里将具体的表设置对应的主键策略 -->
	<table name="SQLTOY_BIGINT_TABLE" strategy="generator" generator="snowflake"/>
</primary-key>

<type-mapping>
          <!-- 增加雪花算法的演示,自行配置类型对应 -->
	<sql-type native-types="BIGINT"	jdbc-type="BIGINT" java-type="Long" />
</type-mapping>
```

这样就可以了，quickvo里面默认对照BIGINT对应成了Integer，可以通过额外配置调整过来！
下次将其调整过来

**Comment by sglmsn** [comment]
好的，那个set id我发现任何一段的set方法有返回值的时候，在查询的时候都不会有值出现，估计你那边反射是固定拿了void set字段，
我那个链式调用是lombok自动生成的。

**Comment by chenrenfei** [comment]
类型确实不应该是java.sql.Types.Integer

**Comment by chenrenfei** [comment]
下一版将默认匹配BigInteger类型

**Comment by sglmsn** [comment]
那个类型的是次要的,  主要是 set方法的问题, 如果是  public String setName(String name); 这样的方法签名, 会导致查询的结果中, 该对象 的 name 属性没有值

**Comment by sglmsn** [comment]
> 下一版将默认匹配BigInteger类型

那个类型的是次要的, 主要是 set方法的问题, 如果是 public String setName(String name); 这样的方法签名, 会导致查询的结果中, 该对象 的 name 属性没有值

**Comment by chenrenfei** [comment]
为什么会有String setName() 这种方法呢？

**Comment by sglmsn** [comment]
> 为什么会有String setName() 这种方法呢？应该是void setName(String name)

这个, 因为 可以   new User().setName(name).setAge(age).setPhone(phone);
这个比较方便

**Comment by chenrenfei** [comment]
理解，我之前方法映射时限制了是void setXXX的方法，下一版将这个限制条件放开！

**Comment by chenrenfei** [comment]
4.10.9 预览版已经发布，已经解决了这个问题，可以试一试，另外quickvo可以直接生成:
参考:showcase 下面的quickvo.xml 配置
```java
public VO setName(String name)
{ 
    this.name=name;
    return this;
}
```
