### ISSUE TITLE
有1对n关联查询的结果映射相关的文档吗?

### ISSUE THREAD

**Issue by zohar-soul** [chenrenfei/sagacity-sqltoy#14]
查了一圈没找到.

顺便问下为什么生成的vo既然不允许修改

>  sqltoy 生成vo分成2部分:AbstractVO 和 VO,AbstractVO 不允许手工改动保持跟数据库一致，

那么为什么不使用apt来生成呢? 这样既避免了繁琐的配置,又能防止不小心手工改动了.

**Comment by chenrenfei** [comment]
1对n，当数据库表有外键关系就会自动生成

**Comment by chenrenfei** [comment]
你是想手工创建1对n的关联？
1、vo是可以修改的，1对n的配置也可以在vo层级自己来配置，但并不建议。
2、quickvo会覆盖abstractvo，但不会覆盖vo（只会对构造函数部分进行覆盖）

**Comment by chenrenfei** [comment]
如果有外键关系，quickvo会自动生成1对n的关系，而且sqltoy级联操作并不像其他的，尤其是批量级联时，是考虑了数据库交互性能问题的，是批量加载。

```java
/**
	 * 主键关联子表信息
	 */
	@OneToMany(fields={"triggerId"},mappedTable="cron_trigger_task",mappedColumns={"TRIGGER_ID"},mappedFields={"triggerId"})
	protected List<TriggerTaskVO> triggerTaskVOs=new ArrayList<TriggerTaskVO>();

	/**
	 * 主键关联子表信息
	 */
	@OneToMany(fields={"triggerId"},mappedTable="cron_trigger_depend_tasks",mappedColumns={"TRIGGER_ID"},mappedFields={"triggerId"})
	protected List<TriggerDependTasksVO> triggerDependTasksVOs=new ArrayList<TriggerDependTasksVO>();

```

**Comment by zohar-soul** [comment]
可能是我把这两个一起问对你产生了误导,这是两个不相关的问题.
先说第一个,我的意思是如何把一对多的查询结果映射到java对象中,这个没找到相关文档

**Comment by chenrenfei** [comment]
你通过User 里面getOrderList就可以了
1、User loadUser()
2、User.getOrderList()

**Comment by zohar-soul** [comment]
@chenrenfei 
那这样不就是查询了两次吗?
可以将sql的结果解析到这样的pojo中么?

**Comment by chenrenfei** [comment]
那你就直接用sql查询明细不就可以了，然后映射到对象里面
findBySql(sql,OrderVO)

**Comment by chenrenfei** [comment]
用qq聊

**Comment by zohar-soul** [comment]
@chenrenfei 
ok 你qq多少我加你?

**Comment by chenrenfei** [comment]
有qq群

**Comment by zohar-soul** [comment]
忘了更新回复了, 作者表示不支持.也不会支持.

**Comment by chenrenfei** [comment]
请你用apt给我们演示一下如何生成PO或VO可以吗？我们也了解一下apt怎么简单可以代替quickvo一个简单的配置和bat执行

**Comment by zohar-soul** [comment]
> 请你用apt给我们演示一下如何生成PO或VO可以吗？我们也了解一下apt怎么简单可以代替quickvo一个简单的配置和bat执行

我上面回复指的是关联查询，我编辑一下回复。

**Comment by zohar-soul** [comment]
> 请你用apt给我们演示一下如何生成PO或VO可以吗？我们也了解一下apt怎么简单可以代替quickvo一个简单的配置和bat执行

对于apt来说，可以参见Google的room项目。

**Comment by chenrenfei** [comment]
1、sqltoy支持级联加载、级联保存和更新
2、sqltoy有quickvo通过数据库生成vo，这个只是工具简单配置即可并无较大工作量，跟用什么生成并不是核心问题（我不清楚apt如何生成，也认为没有必要使用apt生成）
3、请去深入了解mybatis的主子表级联必定是2次查询，这里的2次不是开发2次调用，而是数据库做了2次sql查询。

apt你演示一下吧，就从数据库生成一个pojo！

**Comment by zohar-soul** [comment]
> 1、sqltoy支持级联加载、级联保存和更新
> 2、sqltoy有quickvo通过数据库生成vo，这个只是工具简单配置即可并无较大工作量，跟用什么生成并不是核心问题（我不清楚apt如何生成，也认为没有必要使用apt生成）
> 3、请去深入了解mybatis的主子表级联必定是2次查询，这里的2次不是开发2次调用，而是数据库做了2次sql查询。
> 
> apt你演示一下吧，就从数据库生成一个pojo！
> 

我觉得你这不是交流反馈的态度 issue close了吧。

**Comment by chenrenfei** [comment]
1、quickvo不只是生成get set，我估计你大体想说的是Lombok通过简单的注解生成get set
2、quickvo生成的是跟数据库相关的信息，有@ID  @Column等注解。分成2个类是有道理的，抽象类用于完全对应数据库，非抽象类可以自行扩展属性。

是问题被你带偏了，原本交流级联处理，重点转向了pojo生成工具上了

**Comment by zohar-soul** [comment]
> 1、quickvo不只是生成get set，我估计你大体想说的是Lombok通过简单的注解生成get set
> 2、quickvo生成的是跟数据库相关的信息，有@id @column等注解。分成2个类是有道理的，抽象类用于完全对应数据库，非抽象类可以自行扩展属性。
> 
> 是问题被你带偏了，原本交流级联处理，重点转向了pojo生成工具上了

嗯 我的问题,我把主楼编辑一下,防止影响后面看到的,
顺便一提mybatis是支持1对n查询一次的,但是我无意,最近也没精力写个demo正面这个,
你有兴趣可以试一下..

**Comment by chenrenfei** [comment]
1对n查询，主表需要查询一次，然后查询子表一次，你可能说的是只查询子表吧！
除非一种可能：一个sql关联查询2张表的全部字段。这个可以一次查询，但这种一次查询会比骂死！

**Comment by zohar-soul** [comment]
@chenrenfei 
然而并不是你想的那样..有没有什么做法自己试下看下执行出来的sql不就知道了..

要面对事实,而不是激动的一顿分析.

**Comment by zohar-soul** [comment]
随便一搜下很难吗?
https://www.google.com/search?q=mybaits+1%E5%AF%B9%E5%A4%9A%E5%85%B3%E8%81%94%E6%9F%A5%E8%AF%A2&oq=mybaits+1%E5%AF%B9%E5%A4%9A%E5%85%B3%E8%81%94%E6%9F%A5%E8%AF%A2&aqs=chrome..69i57j0l2.7970j0j4&sourceid=chrome&ie=UTF-8

各种现成的例子在眼前,我现在越来越觉得我这是浪费时间的行为...
就算我给你讲清楚了这个又有什么意义呢.
