### ISSUE TITLE
spring yml文件配置你的com包名找不到 我看你不是org开头的包名吗？

### ISSUE THREAD

**Issue by OvedayBySnow** [chenrenfei/sagacity-sqltoy#16]
![image](https://user-images.githubusercontent.com/44091130/79719322-e56c0b00-8310-11ea-9103-fb8b6afedc7b.png)

如图上的配置  根据你的官方文档来的 是不是我这边还少了点啥？

**Comment by chenrenfei** [comment]
sqltoy包是org开头的，找不到的是扩展型的，是根据项目实际情况自己定义的部分，主要是用于对通用属性进行赋值，比如单据操作人和最后操作时间等，这些属性在项目中是有意义的！

**Comment by chenrenfei** [comment]
参见showcase项目中的范例代码
