### ISSUE TITLE
SaveOrUpdate方法，希望能够指定条件判断列

### ISSUE THREAD

**Issue by liwei6797** [chenrenfei/sagacity-sqltoy#17]
目前的SaveOrUpdate方法只能根据主键列做条件判断，希望能够自己指定条件判断列，谢谢

**Comment by chenrenfei** [comment]
在一定场景下确实有必要，五一解决这个问题

**Comment by chenrenfei** [comment]
这个问题整体评估了一下，发现必要性不是特别高，目前应该是oracle、db2、mssql可以做到支持，要做到全部数据库通用化支持影响面还是比较大的，建议通过batchUpdate 自定义一个merge 语句用对象来批量执行！
