### ISSUE TITLE
请问对 elasticsearch 的支持如何 ？

### ISSUE THREAD

**Issue by iweisi** [chenrenfei/sagacity-sqltoy#2]
可以支持对elasticsearch的查询吗？

**Comment by chenrenfei** [comment]
支持的，两种支持模式:基于elasticsearch-sql插件模式的，一种是elasticsearch原生json查询语句模式的

**Comment by chenrenfei** [comment]
elasticsearch支持已经在项目中使用，并得到了很好的验证，配合elastisearch-sql插件极为简单

**Comment by chenrenfei** [comment]
<eql id="sys_elastic_test" fields="chineseName,price,trademarkId" >
		<value>
		<![CDATA[
			select * from goods_index
			where 1=1
			#[and chineseName =matchPhrase(:keyword)]
			#[and manufacturerName =matchPhrase(:keyword2)]
			#[and trademarkName =matchPhrase(:keyword3)]
			#[and goodsCateId in (:goodsCateIds)]
			#[and transactionType =:transactionType]
			#[and trademarkId =:trademarkId]
			#[and uom =:uom]
			#[and :endPrice >=price]
			#[and price >=:startPrice]
			#[@if(:priceSort==1 && :transactionSort==1) order by price desc,days desc,upTime desc]
			#[@if(:priceSort==0 && :transactionSort==0) order by price asc,days asc,upTime desc]
			#[@if(:priceSort==1 && :transactionSort==0) order by price asc,days asc,upTime desc]
			#[@if(:priceSort==0 && :transactionSort==1) order by price asc,days asc,upTime desc]
		]]>
		</value>
	</eql>

**Comment by chenrenfei** [comment]
<eql id="sys_elastic_test_json" fields="organ_id,organ_name,create_time">
		<value>
		<![CDATA[
			{
				    "_source": [
				    	"organ_id",
						"organ_name",
						"create_time"
				    ], 
				    "query": {
				        "bool":{
					        "filter":[
					        	<#>{"terms":{"organ_id":[@(:organIds)]}}</#>
					        ]
				        }
				    }
				}
		]]>
		</value>
	</eql>
