### ISSUE TITLE
2个建议：SQL打印和IDE支持改善

### ISSUE THREAD

**Issue by CodingOX** [chenrenfei/sagacity-sqltoy#22]
# SQL打印
项目支持SQL打印，但是打印方式显得有些“鸡肋”，原始的语句和sql参数是分别显示出来的。
为什么不拼接好之后再打印了？如果开发者需要在数据库里面重现这个SQL，当参数多的时候，这个参数替换起来狠不友好。

# IDE支持
当前的IDE的插件功能只有一个关联方法的和XML的功能。是否考虑继续完善了。
- `#[]`语法支持，在我这里，IDE其实在提示错误，如下图所示。
- 结合Intellij 完成 SQL中字段的智能提示。
![image](https://user-images.githubusercontent.com/9800933/84571788-34da2f00-adc8-11ea-903f-ec0f1875e89b.png)

**Comment by chenrenfei** [comment]
sql日志会计划优化一下
idea插件不是我开发的，是其他网友开发的，可以到他的gitee上提一下意见

**Comment by chenrenfei** [comment]
4.12.11 版本将解决日志输出问题

**Comment by chenrenfei** [comment]
4.12.11 已经发版已经解决日志输出问题
