### ISSUE TITLE
load方法时，如果有mysql关键字则报语法错误

### ISSUE THREAD

**Issue by codefalse** [chenrenfei/sagacity-sqltoy#23]
MySQLSyntaxErrorException: You have an error in your SQL syntax;
比如：select desc from test where id = ? 通过load方法自动生成的sql语句，此desc为mysql数据库关键字。
正确语句：select `desc` from test where id = ?
建议将所有生成的sql语句查询字段都加上``，以防止关键字问题

**Comment by chenrenfei** [comment]
你好，要通过reservedWords 来指定项目中使用了哪些关键词

# 数据库保留字兼容处理(原则上不要使用数据库保留字,多个用逗号分隔)
spring.sqltoy.reservedWords=maxvalue,minvalue
