### ISSUE TITLE
请教多租户如何切换数据源？

### ISSUE THREAD

**Issue by pengshaomin** [chenrenfei/sagacity-sqltoy#24]
请教多租户如何切换数据源？

**Comment by chenrenfei** [comment]
参见文档里面的sharding-datasourcee

**Comment by chenrenfei** [comment]
https://github.com/chenrenfei/sqltoy-showcase/tree/master/trunk/sqltoy-sharding

**Comment by pengshaomin** [comment]
是，感谢回答

**Comment by chenrenfei** [comment]
我们系统也是多租户模式的，我们是通过所有表里面增加一个字段模式，来实现租户隔离的
