### ISSUE TITLE
sql multi colunms and dynamic prameters combination translation mapping to an specific value 

### ISSUE THREAD

**Issue by daselang** [chenrenfei/sagacity-sqltoy#25]
Version:4.13.1 or earlier
Now due to  the mechanism of  the sql translation mapping with sql data cache,we can only translate an specicic column to a value instead of Left join sql or writing java codes with same purpose,But there are some scenarios that the current mechanism can't work with.
For in some multi-language scenarios,or in the composite keys/composite columns ,several columns or several dynamic parameters or all the columns and parameters combiation can only mapping to an specific translation value,this orm-framework can't work with it well.
In my opnion,we can wite the sql template just like ,
`Select (column1 column2 ....   :param1 :param2 ...) columnName` instead of `Select colunm1 columnName` ,
which indicates that  the combination of multi colunm or java parameter with : is the final key which can be used to map to the final translation values as before.
That is my suggestion,you can follow this idea and add it to the orm-framework as you like,wharever.

**Comment by chenrenfei** [comment]
计划下一版可以让开发者在代码层面加入缓存翻译，针对特殊场景由开发者来动态设置缓存翻译，为程序提供更多的灵活空间!

**Comment by chenrenfei** [comment]
4.13.5 版本里面已经支持
