### ISSUE TITLE
如何支持mongo

### ISSUE THREAD

**Issue by cmdares** [chenrenfei/sagacity-sqltoy#8]
如何支撑mongo，请给出几个常用的实例。
再多问下，mongo如果两个集合关联咋搞？能否也给个例子。
感谢！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chenrenfei** [comment]
等几天我提供一下，电脑换了没有安装mongodb

另外mongodb只支持查询，而且mongodb现在用的人比较少，查询不支持sql感觉没有啥前景。
另外mongodb是不支持collection关联的，只能单表，建议还是了解一下clickhouse吧，大规模查询这个比较强大

**Comment by chenrenfei** [comment]
请参考4.12.6发版说明里面show使用
