### ISSUE TITLE
是否支持一个片段多句sql，带有事务的情况

### ISSUE THREAD

**Issue by cmdares** [chenrenfei/sagacity-sqltoy#9]
不想写复杂的dao，想通过一个sql片段，一步到位，比如
id1
    sql1 update....
    sql2 delete.....
    sql3 update.....
调用id1的脚本后，传入相关对象，如果都正确则返回，如果一个错误全回滚。目前只考虑同一个数据库的情况，多库事务相对麻烦，可以后期考虑。
您看看，目前软件是否能够解决这个问题。
谢谢。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chenrenfei** [comment]
sqltoy-orm不只是执行sql，还有类似hibernate的crud功能，而且默认提供了
SqlToyLazyDao 和SqlToyCRUDService两个实现。
原则上sqltoy不鼓励大家写Dao,只需写Service，而且简单的表增删改查也不需要写在servcie里面，直接SqlToyCRUDService就可以完成了。

片段式场景不是很明确，sql正常情况下针对查询和特定逻辑修改(而不是普通的记录修改)。

Sqltoy并不是全部玩sql，手工写sql，还是希望一种平衡，普通的表增删改load还是基于对象操作更符合大众思维。
